// Code generated by hertz generator.

package domprinter

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitprintcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _helloMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitprinttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fetchprinttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprinttaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
